name: Build

on:
    push:
      branches:
        - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build

      - name: Release
        run: |
          gh release upload release --clobber build/libs/hit-swap-fix-1.21.4.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
